sudo: false
matrix:
  include:
    - language: node_js
      cache: yarn
      node_js: node

    - language: node_js
      cache: yarn
      node_js: lts/*

addons:
  apt:
    packages:
      - libvips-dev
